// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckNodeJS():Promise<string>;

export function GenerateApplication(arg1:string):Promise<void>;

export function GetApplications():Promise<Array<main.Application>>;

export function GetSelectedApplication():Promise<main.Application>;

export function InsertApplication(arg1:string):Promise<void>;

export function SelectApplication(arg1:number):Promise<void>;

export function SelectFolder():Promise<string>;

export function UpdateSetting(arg1:string):Promise<void>;
