// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckNodeJS() {
  return window['go']['main']['App']['CheckNodeJS']();
}

export function GenerateApplication(arg1) {
  return window['go']['main']['App']['GenerateApplication'](arg1);
}

export function GetApplications() {
  return window['go']['main']['App']['GetApplications']();
}

export function GetSelectedApplication() {
  return window['go']['main']['App']['GetSelectedApplication']();
}

export function InsertApplication(arg1) {
  return window['go']['main']['App']['InsertApplication'](arg1);
}

export function SelectApplication(arg1) {
  return window['go']['main']['App']['SelectApplication'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}

export function UpdateSetting(arg1) {
  return window['go']['main']['App']['UpdateSetting'](arg1);
}
