// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckNodeJS() {
  return window['go']['main']['App']['CheckNodeJS']();
}

export function GetApps() {
  return window['go']['main']['App']['GetApps']();
}

export function InsertApp(arg1) {
  return window['go']['main']['App']['InsertApp'](arg1);
}

export function SelectFolder() {
  return window['go']['main']['App']['SelectFolder']();
}
