// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function CheckNodeJS():Promise<string>;

export function GetApps():Promise<Array<main.Application>>;

export function GetSelectedApp():Promise<main.Application>;

export function InsertApp(arg1:string):Promise<void>;

export function SelectApp(arg1:number):Promise<void>;

export function SelectFolder():Promise<string>;
