// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {notion} from '../models';

export function CheckNodeJS():Promise<string>;

export function GenerateApplication(arg1:string):Promise<void>;

export function GenerateCSVFromNotionDatabase(arg1:string):Promise<void>;

export function GetApplications():Promise<Array<main.Application>>;

export function GetNotionDatabase(arg1:string,arg2:string):Promise<notion.Database>;

export function GetSelectedApplication():Promise<main.Application>;

export function ImportCSVFileForNotionDB(arg1:Array<number>,arg2:string):Promise<void>;

export function InsertApplication(arg1:string):Promise<void>;

export function SelectApplication(arg1:number):Promise<void>;

export function SelectFolder():Promise<string>;

export function UpdateSetting(arg1:string):Promise<void>;
